version: "3.0"
services:
  spark-master:
    image: bde2020/spark-master:2.3.1-hadoop2.7
    ports:
      - "8080:8080"
      - "7077:7077"
      - "4040:4040"
    volumes:
      - "/media/sf_data:/data"
      - ".:/shared"
    environment:
      - INIT_DAEMON_STEP=setup_spark
    deploy:
      placement:
        constraints: [node.role == manager]
  # spark-worker-1:
  #   image: bde2020/spark-worker:2.3.1-hadoop2.7
  #   depends_on:
  #     - spark-master
  #   ports:
  #     - "8081:8081"
  #   volumes:
  #     - "/media/sf_data:/data"
  #   environment:
  #     - "SPARK_MASTER=spark://spark-master:7077"
  # spark-worker-2:
  #   image: bde2020/spark-worker:2.3.1-hadoop2.7
  #   depends_on:
  #     - spark-master
  #   ports:
  #     - "8082:8081"
  #   volumes:
  #     - "/media/sf_data:/data"
  #   environment:
  #     - "SPARK_MASTER=spark://spark-master:7077"

